server:
  port : 8222
  servlet:
    context-path: /gatewayB
spring:
  application:
    name: spring-cloudB #服务名
eureka:
  client:
    service-url:
      # 注册中心服务端地址
      defaultZone: http://localhost:8888/eureka/
# 监控中心调用配置
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
