server:
  port : 8222
  servlet:
    context-path: /gatewayB
spring:
  zipkin:
    #zipkin服务地址 即上面的使用docker启动服务或jar包启动的服务
    base-url: http://127.0.0.1:9411/
    sender:
      #http方式传输数据到zipkin
      type: web
    service:
      #服务名称 order为订单系统，express为快递系统
      name: express
    sleuth:
      sampler:
        #取样比例 1为每次都将数据传入Zipkin 默认为0.1
        probability: 1
  application:
    name: spring-cloudB #服务名
eureka:
  client:
    service-url:
      # 注册中心服务端地址
      defaultZone: http://localhost:8888/eureka/
# 监控中心调用配置
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
